version: "3.8"

services:
        ai-app:
          image: ai
          container_name: ai-app
          restart: always
          ports:
               - 8000:8000

networks:
        default:
                name: voicescout
                external: true
